boostcampwm-2024/web27-Preview

frontend/src/routes.tsx

- 세션 리스트, 세션 생성, 세션 채널, 로그인, 에러 페이지를 라우팅

[기능 추가] 협업을 위한 라우터 설정

---

frontend/package.json
frontend/src/App.tsx
frontend/src/main.tsx
frontend/src/routes.tsx
pnpm-lock.yaml

- 간단한 비디오 켜기 기능 구현
- SPA 라우팅을 설정해놓고, 각 페이지를 분담해 UI를 구현할 계획
- 세션 리스트, 세션 생성, 세션 채널, 로그인, 에러 페이지를 라우팅

[기능 추가] 프론트엔드 협업을 위한 react-router 설치 및 간단한 비디오 켜기 기능 구현

---

frontend/package.json
frontend/src/components/common/ProgressBar.tsx
frontend/src/components/common/Toast.tsx
frontend/src/components/common/ToastProvider.tsx
frontend/src/hooks/useToast.ts
frontend/src/index.css
frontend/src/main.tsx
frontend/src/pages/SessionListPage.tsx
frontend/src/stores/useToastStore.ts
pnpm-lock.yaml

> [!NOTE]
> 작성자: 서정우
> 작성 날짜: 2024.11.12
- 화면의 우측 상단에 토스트 메시지를 띄워 사용자에게 정보를 전달
- useToast 커스텀 훅과 useToastStore Zustand 스토어를 사용해서 어떤 위치에서도 Toast 메시지를 사용할 수 있도록 구현
- 토스트 메시지는 가려지지 않아야하므로, root 레벨에서 ToastProvider 컴포넌트에서 렌더링
- 토스트 메시지는 기본 5초 뒤에 사라지고, 사용자가 임의로 종료 가능
- 토스트 메시지의 종료 시점은 프로그레스바로 예측할 수 있도록 구현
- [작업문서](https://alpine-tiglon-9f0.notion.site/13c696f85d1f80e88314e9ed005b3ff7?pvs=4)
- 전체 토스트 메시지는 useToastStore Zustand 스토어에서 관리한다.
- 루트 단에서 렌더링할 때는 Zustand 스토어에서 toasts를 가져와서 렌더링하도록 한다.
- 사용자와 상호작용하고 싶은 어디든 useToast 훅에서 `toast.success`, `toast.error` 함수를 통해 토스트메시지를 간편하게 생성할 수 있다.
```tsx
// hook 불러와서
const toast = useToast();
// 사용
return <p>{toast.success('메시지')}</p>
```
```tsx
// 예시
toast.success("세션에 참가했습니다.");
```
- 현재는 임시로 세션에 참가했을 때 토스트메시지를 사용하도록 설정

[Feat] 토스트 메시지 커스터 훅 구현 및 전역적인 토스트 메시지 관리 스토어 구현

---

frontend/src/components/sessions/SessionCard.tsx
frontend/src/pages/SessionListPage.tsx

> 작성자: 서정우
> 작성 날짜: 2024.11.20
- 세션 정보 수정을 예상하고 작성했습니다.
- 호스트 정보 추가
- inProgress 속성 추가
- status 속성 삭제 (어차피 렌더링되는 것은 public 세션 뿐이기 때문에)

[Feat] 세션 리스트 렌더링 함수 구현 및 세션 데이터 구조 변경

---

backend/src/app.module.ts
backend/src/config/typeorm.config.ts
backend/src/question-list/category.entity.ts
backend/src/question-list/dto/create-question-list.dto.ts
backend/src/question-list/dto/get-all-question-list.dto.ts
backend/src/question-list/dto/question-list.dto.ts
backend/src/question-list/question-list.controller.ts
backend/src/question-list/question-list.entity.ts
backend/src/question-list/question-list.module.ts
backend/src/question-list/question-list.repository.ts
backend/src/question-list/question-list.service.ts
backend/src/user/user.module.ts

> - 작성자: 송수민
> - 작성 날짜: 2024.11.20
- #132
- #131
- #130
- #129
- #180 
- #183 
- #185
- 문지 생성 기능에 태그 추가해서 구현
- 전체 공개 질문지 조회 구현
- 카테고리별 공개 질문지 검색 기능 구현
- 요청할 때 카테고리 리스트도 함께 받아오도록 구현하고 API 명세서도 업데이트했습니다.
- 받아온 카테고리 이름으로 디비에 접근해서 카테고리 데이터들을 가져옵니다.
- 만약 존재하지 않는 카테고리를 요청하면 에러가 발생합니다.
```ts
// question-list.service.ts
async createQuestionList(createQuestionListDto: CreateQuestionListDto) {
const { title, categoryNames, isPublic, userId } =
createQuestionListDto;
const categories =
await this.questionListRepository.findCategoriesByNames(
categoryNames
);
if (categories.length !== categoryNames.length) {
throw new Error("Some category names were not found.");
}
const questionListDto: QuestionListDto = {
title,
categories,
isPublic,
userId,
};
return …
```

[Feat] 질문지 생성, 조회, 검색 기능 구현

---

backend/src/auth/auth.service.spec.ts
backend/src/redis/redis.service.spec.ts
backend/src/room/room.controller.spec.ts
backend/src/room/room.gateway.spec.ts
backend/src/room/room.repository.ts
backend/src/room/room.service.spec.ts

> - 작성자:  김찬우
> - 작성 날짜: 2024.11.19
- 전반적인 백엔드 코드 테스트 코드를 작성했습니다.
전반적인 작업을 AI와 함께 진행했기 때문에 코드를 모두 커버하진 못합니다.
다만, 비즈니스 로직에 대한 `Edge case` 는 테스트할 수 있습니다.
- 단순 `Repository` 는 작성하지 않음
- 비즈니스 로직이 필요한 부분에서는 작성 완료함
- 단순히 호출을 하는지와 로직만 확인하므로, 자세한 테스트 코드는 다시 직접 작성해야함
- 방 리스트가 없을 경우 빈 객체 반환하도록 수정
커버리지를 100% 현재로썬 달성할 수 있게 코드를 만들었습니다.
- 현재 AI로 코드를 작성했는데, 생각보다 좋아서 놀랐습니다.
- 이후 리팩토링하면서 스펙을 다시 수정을 할텐데, 이때 제대로 모킹을 배워보겠습니다.
- 모킹에 관한 개념이 아직 와닿지가 않았는데, 이번 기회에 조금은 알게 된 것 같습니다.
- 현재 AI와 같이 코드를 작성해두었는데, 이상한 부분이 있으면 알려주세요~

[Test] 백엔드 테스트 코드 추가

---

frontend/src/constraints/LayoutConstant.ts
frontend/src/hooks/useToast.ts
frontend/src/pages/CreateSessionPage.tsx
frontend/src/pages/SessionListPage.tsx
pnpm-lock.yaml

> [!NOTE]
> - 작성자: 서정우
> - 작성 날짜: 2024.11.21
- 세션 생성 페이지에 사이드바 추가
- 사이드바가 있어야하는 페이지 최상단 태그 전용 스타일 constraint로 분리
- 로딩 인디케이터 추가
- 간단한 작업입니다. 사이드바를 추가하고 싶은 페이지에서 아래처럼 sectionWithSidebar 를 import해서 써주시면 됩니다.
```tsx
import Sidebar from "@components/common/Sidebar.tsx";
import { sectionWithSidebar } from "@/constraints/LayoutConstant.ts";
return (
<section className={`${sectionWithSidebar}`}>
<Sidebar />
<div className={"p-20"}>
<button
className="flex items-center gap-4 mb-5 text-gray-black text-medium-l"
onClick={() => navigate("/sessions")}
>
<IoArrowBackSharp className="w-5 h-5" />
<span>면접 채널로 돌아가기</span>
</button>
<h1 className="text-bold-l mb-2">새로운 스터디 세션 만들기</h1>
<p className="text-medium-l text-gray-400 mb-8">
면접 스터디를 위한 새로운 세션을 생성합니다.
</p>
<SessionForm />
</div>
</section>
);
```
- …

[Refactor] 세션 생성 페이지 사이드바 추가 및 로딩 추가

---

frontend/index.html
frontend/public/preview-logo.svg

> [!NOTE]
> 메타데이터 수정했습니다. Title 좀 더 직관적으로 수정했고, 오픈 그래프라고 이제 저희 배포링크 카톡이나 디코에 붙여넣기하면 이미지나 설명이 뜨게 했습니다. 파비콘 추가했고, 검색엔진을 위해 메타데이터 추가하고, 서비스 description 추가했습니다.
- 앞에서 언급한 내용만 간단하게 추가했습니다.
로고....................

[Feat] 페이지 메타데이터 수정 및 오픈그래프, 파비콘 추가 등

---

frontend/src/pages/SessionListPage.tsx

> - 작성자: OOO
> - 작성 날짜: YYYY.MM.DD
- (이슈 번호 작성) # 
- 작업한 주요 기능 및 수정 사항
- 하루 동안 진행된 핵심적인 변경사항 간단 정리
- 상세 설명: 작업 목적, 사용한 기술, 문제 해결 방법, 고려한 사항 등
- 관련 코드 예시가 있다면 포함
- 상세 설명: 작업 목적, 사용한 기술, 문제 해결 방법, 고려한 사항 등
- 관련 코드 예시가 있다면 포함
- 변경 사항을 테스트하거나 검증한 방법, 간단한 결과 설명
- 관련 스크린샷, 영상이 있다면 첨부
- 내일 또는 이후에 진행할 예정인 작업
- 추가적인 개선 사항이나 논의가 필요한 내용
- [참고한 자료 제목](링크)
- [참고한 자료 제목](링크)
- 리뷰 받고 싶은 부분이 있다면 작성

[Fix] Select 컴포넌트 Props 오류 해결

---

frontend/src/pages/SessionListPage.tsx

> [!NOTE]
> main에는 머지됐는데 dev에는 없어서 dev에 merge하기 위해서 작성합니다.
> - 작성자: 서정우
> - 작성 날짜: 2024.11.26
- Select 컴포넌트 Props 수정으로 인한 이슈

[Fix] select 컴포넌트 관련 오류 해결

---

backend/src/room/dto/create-room.dto.ts
backend/src/room/dto/room.dto.ts
backend/src/room/room.controller.ts
backend/src/room/room.entity.ts
backend/src/room/room.gateway.ts
backend/src/room/room.repository.ts
backend/src/room/services/room-create.service.ts
backend/src/room/services/room-host.service.ts
backend/src/room/services/room-join.service.ts
backend/src/room/services/room-leave.service.ts

> [!important]
> 
> 명세서가 바뀌는 작업을 리뷰할 때, `반드시 명세서를 확인해주세요.`
> `머지되는 브랜치도 확인해주세요!`
> 저도 실수할 때가 있으니 바뀌는 명세가 있을 수 있습니다.
>
> **바뀐 명세서는 [이곳](https://alpine-tiglon-9f0.notion.site/API-2-0-b68c34cc3b2643d4bbaa950351067ebe?pvs=4) 에서 확인해주세요.**
> - 작성자: 김찬우
> - 작성 날짜: 2024.11.26
- 카테고리 필드 추가
- 명세에 맞게 DTO 수정

[Fix] category 필드 추가, 명세에 맞게 엔티티 DTO 수정

---

backend/src/room/dto/room-list.dto.ts
backend/src/room/dto/room.dto.ts
backend/src/room/room.entity.ts
backend/src/room/room.repository.ts
backend/src/room/services/room-create.service.ts
backend/src/room/services/room.service.ts

- 세션 리스트 API 에 질문지 이름 항목 추가
- 카테고리 배열로 반환되는데 명세서에 업데이트 안되어서 업데이트 했습니다.
- 이부분은 얘기된거라 알고 계실거라고 생각합니다.. (아니면..어..)
- 영향받는 방 생성 참가 까지 테스트했습니다.
- 통합하여 테스트하였고 잘 작동했습니다.
- 단위 테스트부터 통합 테스트까지 주말 중으로 작성 예정이므로 앞으로 검증 결과가 명확해질 것입니다.
- DTO 에 대해서 조금 잘못 사용하고 있어서 이 부분 리팩토링 예정입니다.
- 리팩토링 후, 테스트 코드 작성하여 스펙 동결하고, 클래스 다이어그램 작성 후 동결 예정입니다.

[Feat] 세션 리스트 API 에 질문지 이름 항목 추가

---

backend/src/room/services/room-create.service.ts

- 스터디 세션 생성 시 사용량 업데이트 로직 추가
- 아래 요청을 반영합니다
- `@Transactional()` 데코레이터를 사용해서 트랜잭션을 수행 하도록 합니다.
- 웹소켓 emit 과 구별할 수 있도록 리팩토링할 예정입니다.
- 세션 생성마다 필드 업데이트가 잘 되고 있는 걸 프론트엔드에서 테스트로 확인했습니다.

[Feat] 스터디 세션 생성 시 사용량 업데이트 로직 추가

---

backend/src/user/user.service.ts

- 명세서에 맞게 로그인 타입 반환값 수정 
- 추후에 API 명세서 출력값을 DB에 맞게 전부 통일 필요
- 리팩토링 기간 중 `swagger` 도입 예정

[Fix] 명세서에 맞게 로그인 타입 반환값 수정 

---

README.md

- 리드미 업데이트 
- 문서나 그라운드룰은 빼고, 핵심 기능 추가, 팀원 소개 아래로 내렸습니다.
- 수정하셔도 됩니다

[Docs] 리드미 업데이트

---

frontend/src/pages/Login/hooks/useValidate.ts
frontend/src/pages/Login/view/DefaultAuthFormContainer.tsx

> - 작성자: 서정우
> - 작성 날짜: 2024.12.01
- 로그인 아이디, 닉네임에 대한 중복처리를 강화
```tsx
if (isAxiosError(err)) {
const { response } = err;
if (response?.status === 401) {
toast.error("아이디 또는 비밀번호가 일치하지 않습니다.");
} else {
toast.error("로그인에 실패했습니다. 잠시 후 다시 시도해주세요.");
}
} else console.error("로그인 도중 에러", err);
```
```tsx
const { code } = response.data;
switch (code) {
case "DUPLICATE_NICKNAME":
toast.error("이미 존재하는 닉네임입니다.");
break;
case "DUPLICATE_ID":
toast.error("이미 존재하는 아이디입니다.");
break;
default:
toast.error(
"회원가입에 실패했습니다. 잠시 후 다시 시도해주세요."
);
break;
}
```

[Fix] 로그인 필드 중복 에러 처리

---

frontend/src/components/common/TitleInput/index.tsx
frontend/src/components/sessions/create/SessionForm/TitleSection/index.tsx
frontend/src/pages/SessionPage/hooks/usePeerConnection.ts

[Fix] 빌드에러 수정

---

frontend/src/components/common/TitleInput/index.tsx
frontend/src/components/sessions/create/SessionForm/TitleSection/index.tsx
frontend/src/pages/SessionPage/hooks/usePeerConnection.ts

[Fix] 빌드 에러 수정

---

frontend/public/robots.txt
frontend/src/components/questions/QuestionsPreviewCard.tsx
frontend/src/index.css
frontend/src/pages/Login/LoginPage.tsx
frontend/src/pages/Login/hooks/useValidate.ts
frontend/src/pages/Login/view/DefaultAuthFormContainer.tsx

> [!NOTE]
> 로그인 throttle 최적화, OS기본 다크모드 비활성화, robots.txt 추가
> - 작성자: 서정우
> - 작성 날짜: 2024.12.03
- 로그인 throttle 최적화
- 운영체제 다크모드 비활성화
- robots.txt 추가
- 회원가입할 때 원래 토스트 메시지가 우수수 떴던 걸 회원가입 윗칸에 오류 메시지를 작게 출력하도록 변경했습니다.
- 여러개의 오류가 떠도 제일 첫번째 에러만 뜨도록 했습니다.
lodash 라이브러리의 throttle 함수를 사용했습니다. 시간은 1초로 했고, 1초 이내로 여러번 눌러도 효과가 없도록 최적화했습니다.
```tsx
const handleDefaultLogin = useCallback(
throttle((e: React.MouseEvent<HTMLButtonElement>) => {
try {
e.preventDefault();
if (isSignUp) handleSignUp();
else handleLogin();
} catch (err) {
console.error("로그인 도중 에러", err);
}
}, 1000),
[]
);
```
검색엔진 최적화를 위해 `robots.txt` 작성, 구글과 네이버 검색엔진에 크롤링 가능하도록 작성했습니다.
```text
User-agent: Googlebot
Allow: /
Crawl-delay: 1
User-agent: Yeti
Allow: /
Crawl-delay: 1
User-agent: *
Allow: /
Crawl-delay: 1
```
- 마이페이지 수정 쪽에서 승윤님이 도입한 …

[Refactor] 로그인 throttle 최적화, OS기본 다크모드 비활성화, robots.txt 추가, 비밀번호 보기 기능 추가

---

frontend/src/components/session/VideoProfileOverlay.tsx

- 비디오 오버레이가 비디오 컴포넌트 비디오를 z-10으로 변경되어서 가려졌던 문제를 해결

[Fix] 비디오 오버레이 안보이던 문제 해결

---

backend/src/room/room.service.ts
frontend/src/hooks/useSocket.ts
frontend/src/stores/useSocketStore.ts

> [!NOTE]
> - 작성자: 이승윤
> - 작성 날짜: 2024.12.04
- 소켓 연결 요청 3번가는 오류 수정
실제로 세션 페이지 들어가면 연결 요청이 3번 가고 있었고, 네트워크 탭도 마찬가지였습니다. 
- 그래서 연결 중일 때는 연결을 시도하지 않도록 했습니다.
- 으아아!! 나중에 상세 설명 적겠습니다. 😭
- 코드 변경 사항이 2개 밖에 없으니 이 부분 확인해주시면 될거 같아요.
- 찬우님이 한 번 더 확인해주시면 감사하겠습니다.

[Fix] 소켓 연결 요청 3번 오류 수정

---

frontend/src/components/common/Sidebar/Sidebar.tsx
frontend/vite.config.ts

> [!NOTE]
> 다크모드 비활성화
> - 작성자: 서정우
> - 작성 날짜: 2024.12.05
- 다크모드 버튼 비활성화ㅠㅠ

[Refactor] 다크모드 비활성화 ㅠㅠ

---

backend/package.json
backend/src/question-list/question-list.service.ts
backend/src/question-list/repository/question.respository.ts
backend/test/k6/create-question-list-test.ts
backend/test/k6/delete-question-test.ts

> [!Note]
> - 작성자: 송수민
> - 작성 날짜: 2024.12.05
- TypeScript용 k6 설치
- 트랜잭션 성능 테스트 코드 작성
- 질문 삭제 로직을 테스트 가능하도록 수정
- k6는 Grafana Labs가 운영하는 오픈소스 성능 테스트 도구입니다.
- 자바스크립트로 테스트 시나리오를 작성할 수 있습니다.
- 다행히 타입 스크립트도 지원해주어서 `@types/k6`를 설치해주었습니다.
- 트랜잭션은 질문지 생성, 질문 삭제 로직에 필요합니다.
- 질문지 생성 테스트 시나리오는 다음과 같이 작성해주었습니다.
```ts
import http from "k6/http";
import { check, sleep } from "k6";
export const options = {
vus: 100, // 100명의 사용자
duration: "5s", // 5초 동안 동시 요청을 실행
};
const BASE_URL = "http://localhost:3000";
const COOKIE = "cookie";
const questionListData = { // 함께 전송할 body data
title: "Sample Question List for Test",
contents: [
"This is 1st question!",
"This is 2nd question!",
"This is 3rd question!",
"This is 4th question!",
"This is 5th question!",
"This is 6th question!",
"This is 7th question!", …
```

[Refactor] k6로 queryRunner 적용한 트랜잭션 성능 테스트하기 

---

docker-compose.yml
turnserver.conf

> [!note]
>
> 도커 컴포즈 파일을 변경했기 때문에 도커를 날리고 다시 컴포즈를 올리셔야합니다.
>
- 이제 로컬 환경에서도 정상적으로 실행하실 수 있습니다.
- `frontend/.env` 파일에서 호스트를 `stun:127.0.0.1:3478` 로 접근하면 됩니다.
- 비밀번호, 유저 이름은 비우고 진행해보고 테스트했는데, 혹시 안된다면 비밀번호와 유저 이름을 비우고 해보면 됩니다.

[Chore] coturn 서버 도커화
