boostcampwm-2024/web27-Preview

backend/package.json, backend/src/app.controller.spec.ts, backend/src/app.controller.ts, backend/src/app.module.ts, backend/src/app.service.ts, backend/src/main.ts, backend/src/socket/socket.gateway.ts, backend/src/socket/socket.module.ts
> - 작성자: J141_송수민
> - 작성 날짜: 2024.11.05
- #11 
- WebSocket과 socket.io를 이용한 signaling server 구현 
- join_room 이벤트
- offer 이벤트
- answer 이벤트
- candidate 이벤트
- 웹소켓이 연결되면 로그를 찍고, 연결이 해제되면 해당 방에 있던 나머지 사용자에게 퇴장 이벤트를 보낸다.
```ts
class SocketGateway implements OnGatewayConnection, OnGatewayDisconnect {
@WebSocketServer()
server: Server;
private users: { [key: string]: User[] } = {}; // { '방 이름': [ { id: '소켓id', nickname: '유저 닉네임' }, ... ], ... }
private socketToRoom: { [key: string]: string } = {}; // { '소켓id': '방 이름', ... }
private maximum = 5; // 방 하나에 최대 5명 입장 가능
handleConnection(socket: any) {
console.log(`Client connected: ${socket.id}`);
}
handleDisconnect(socket: any) {
console.log(`Client disconnected: ${socket.id}`);
const roomID = this.socketToRoom[socket.id];
if (roomID) {
const room = …
```
=> Signaling server 구현

frontend/src/App.tsx, frontend/src/components/SessionCard.tsx, frontend/src/components/VideoContainer.tsx, frontend/src/components/VideoRoom.tsx, frontend/src/pages/SessionListPage.tsx
- #11 
- 오디오 송출 버그 수정
- 세션 가득찼을 때의 예외처리 구현
- index로 접근시 sessions 페이지로 리다이렉션
- 해당 버그는 컴포넌트 재사용 과정에서 muted 속성이 재사용되었기 때문에 발생한 오류이다.
- 컴포넌트에 isLocal 상태를 추가하여 본인의 스트림의 경우에만 muted를 적용하고, 다른 사람들의 스트림에는 muted를 적용하지 않는 방식으로 해결했다.
- 문제 상황 : 세션이 가득찼을 경우 마지막에 들어온 유저는 미디어 장치만 켜지고 세션에 입장이 되지 않던 오류
- 시그널링 서버에서 세션에 사람이 가득찬 경우에 발생시키는 `room_full` 이벤트에 대해 핸들러를 추가하는 방식으로 해결
- 세션에 이미 5명이 들어와있고, 그 후에 1명이 더 들어오는 경우
- 오류 메시지를 alert가 아닌 toast 메시지로 구현하면 더 UI/UX가 좋아질 것 같다.
- [webRTC 미디어 관련 예제](https://webrtc.github.io/samples/src/content/getusermedia/audio/)
=> [Fix] 화상회의 오디오 버그, 세션 가득찬 상황 대처에 대한 버그 수정

frontend/src/components/SessionCard.tsx, frontend/src/index.css, frontend/src/pages/SessionListPage.tsx, frontend/tailwind.config.js
> [!NOTE]
> - 작성자: 이승윤
> - 작성 날짜: 2024.11.10
>
> 기존 작업에 디자인만 변경해서 코드 구조라거나 다른 부분은 변경된 사항이 없습니다.
- 세션 카드 컴포넌트 디자인
- 세션 리스트 페이지 디자인
- 원래 세션 카드를 860px로 만들었는데, 피그마 상에서는 괜찮아보였는데 막상 적용하니 너무 카드가 길어 100px 정도 줄였습니다.
- 나중에 왼쪽에 메뉴바가 올 예정이라 조금 줄이는게 나을거 같다 판단했습니다.
- 피그마 상에서는 잘 몰랐는데 막상 적용해보니 폰트가 너무 크다고 느껴졌습니다.
- 그래서 적당히 줄였습니다. 그래도 지금도 적당히 큰 편입니다.
- 그 외) 카드 그림자, 폰트 적용
- px 단위로 적용했던 것을 `rem` 단위로 정의해두었습니다. 
- 누락되어있던 색상 시스템도 추가해서 적용했습니다.
개인적인 생각으로는 면접 연습을 하다보니, 폰보다는 태블릿이나 노트북, 데스크탑으로 이용하는 걸 위주로 고려해야한다 생각을 했습니다. 질문도 봐야하고 다른 사람의 영상도 표시해야하고 그러다보니 폰으로 접속하는 사용자를 고려하지 않아도 되지 않을까 생각했습니다. 줌을 보통 폰으로 이용해서 강의를 들을 때도 답답한데(보통 급한 일 있을 때 줌을 폰으로 이용했었음), 저희는 면접 질문도 띄우고 다른 사람 영상도 다 표시하며 소통하는게 중요하기 때문에 태블릿의 가로 사이즈 정도를 최소 width로 잡고 작업하면 어떨까하는 생각이 들었습니다.
=> [Design] 세션 리스트 페이지 디자인

.github/workflows/deploy.yml
> - 작성자: 김찬우
> - 작성 날짜: 2024.11.09
- 연관된 이슈 번호 없음 (프로젝트 배포)
- `Github Actions` 워크 플로우를 추가했습니다.
- 해당 워크 플로우는 `main` 브랜치가 업데이트 될 때 실행됩니다.
- 클라우드에 `ssh` 로 접속하여 배포 스크립트를 실행합니다.
- 클라우드 서버에 매번 접속하여 배포할 필요가 없도록 했습니다.
- `ssh action` 을 사용하였습니다.
- `sudo` 과정 중 비밀번호 입력을 방지하기 위해 `sudo -S` 옵션을 이용하여 사전에 `sudo` 사용권한을 얻고 시작합니다.
```yml
name: Deploy to Ncloud Server
on:
push:
branches:
- main
jobs:
deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v3.3.0 # workflow 내에서 repo의 최신 코드를 checkout
- name: Deploy to Ncloud via SSH
uses: appleboy/ssh-action@master # GitHub Actions에서 SSH로 서버에 접근
with:
host: ${{ secrets.REMOTE_SSH_HOST }}
username: ${{ secrets.REMOTE_SSH_USERNAME }}
key: ${{ secrets.REMOTE_SSH_KEY }}
passphrase: ${{ secrets.REMOTE_SSH_PASSPHRASE }}
password: ${{ …
```
=> [Feat] 배포 워크플로우 추가

backend/src/socket/socket.gateway.ts, frontend/src/components/session/DisplayMediaStream.tsx, frontend/src/components/session/SessionToolbar.tsx, frontend/src/components/session/VideoContainer.tsx, frontend/src/pages/SessionPage.tsx
> [!NOTE]
> 작성자: 서정우
> 작성 날짜: 2024.11.11
> 관련 에픽: #11 
>
> 공감 기능을 구현했습니다. 수민님이 시그널링 서버 코드를 잘 만들어주셔서 참고해서 시그널링 서버를 중개해서 공감 이벤트를 수신하고 세션에 재발신하도록 하는 방식으로 구현했습니다.
> 공감 기능 자체는 금방 구현했으나 클라이언트에서 비디오컴포넌트 깜빡임 이슈가 있어서 렌더링 최적화를 하느라 시간이 생각보다 지체되었네요..
> 
> 그래도 성과로는 비디오 컴포넌트 렌더링 최적화와 스트림 송출 책임 분리를 얻었습니다.
- 공감 기능 구현
- 비디오 컴포넌트 구조 최적화
- 깜빡임 이슈 해결
- 현재는 thumbs_up 리액션만 존재하지만 추후 확장을 고려해 `reaction` 이벤트에 body에 roomId와 reactionType을 보내도록 구현
- P2P 비디오 컴포넌트 렌더링 과정에서 `useMemo` 훅을 사용하여 peers의 변동이 있을때만 리렌더링 하도록 최적화
- `VideoContainer` 컴포넌트에서 ref를 전달받던 것을 stream을 전달 받아 하위에서 ref를 사용하도록 구조 변경
- `VideoContainer` 컴포넌트 내부 video 태그와 스트림 송출의 역할을 `DisplayMediaStream` 컴포넌트로 분리
- gif를 붙이고 싶은데 용량이 커서 올라가지 않네요..
- 노션에 정리해뒀습니다.
- 정상 작동 확인했습니다. 
- 공감 띄우는 방식은 이모지로 했으나 다른 의견이 있으면 말씀해주시면 조율해보겠습니다.
- [webrtc 리액트 예제, 이거 …
=> [Feat] 공감 기능 구현, 렌더링 최적화와 깜빡임 이슈 해결

frontend/src/hooks/useMediaDevices.ts, frontend/src/hooks/usePeerConnection.ts, frontend/src/hooks/useSocket.ts, frontend/src/pages/SessionPage.tsx
> [!NOTE]
> 관련 이슈 번호: #111 
> 작성자: 서정우
> 작성 날짜: 2024.11.13
- #111 버그 해결
- 카메라/마이크 끄고 켤때 새로운 미디어 스트림을 생성하도록 변경
- **카메라 인디케이터를 비활성화하고 다시켤때 스트림을 다시 얻어오는 작업**
- 이전에는 단순히 비활성화를 했다면 이번에는 **스트림을 새로 생성하기 때문에 약간의 지연시간**이 생겼다.
- [노션 개발 문서](https://alpine-tiglon-9f0.notion.site/13c696f85d1f8077af51d8ded17740a7?pvs=4)
=> [Fix] 카메라를 꺼도 인디케이터가 켜져있던 문제 해결

frontend/src/components/session/SessionSidebar.tsx, frontend/src/components/sessions/create/SessionForm/AccessSection/index.tsx, frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/QuestionItem.tsx, frontend/src/components/sessions/create/SessionForm/ParticipantSection/ParticpantButton.tsx, frontend/src/components/sessions/create/SessionForm/index.tsx, frontend/src/pages/SessionPage.tsx, frontend/vite.config.ts
> - 작성자: 이승윤
> - 작성 날짜: 2024.11.14
- #101 
- #105 
- 백엔드 서버와 연결해서 방 생성 확인
- 만들어진 방 링크로 다른 사용자 접속
- 백엔드 데이터 형식으로 인한 코드 수정
- 세션 만들기에서 create_room으로 서버에 요청하면 서버가 roomId를 주고, 해당 roomId를 이용해 접속한다.
- 상대방도 session/:sessionId를 같이 입력하고 닉네임을 입력하면 같은 방에 접속할 수 있다.
- 기존의 roomId 입력 부분이 이제 필요없어져서 지웠다.
- 입장하면 사용자가 입력한 이름으로 뜨는데, 링크로 들어온 상대는 방 이름을 볼 수가 없다.
- 추후 서버에서 만들어진 방 title도 받아와서 넣는게 필요해보인다.
- 백엔드에서 배열로 소켓 아이디만을 전달해서 화상회의 기능이 동작하지 않았으나, 데이터 형식을 수정해서 그 부분에 맞게 수정한 후 오류가 해결되었다.
- 급하게 작업하느라 코드를 한 번 더 확인할 필요가 있을거 같음
=> [Feat] 세션 만들기 후 방 입장 | 링크 공유해서 들어올 수 있게 설정

frontend/src/components/common/Sidebar.tsx, frontend/src/pages/SessionListPage.tsx
> [!NOTE]
> 작성자: 서정우
> 작성 날짜: 2024.11.19
- 사이드바 공용 컴포넌트 구현
- 피그마에 디자인한 사이드바를 그대로 구현
- 애니메이션, 접근성 라벨 등 추가
- 사이드바 아래에 Preview 리포지토리로 이동하는 링크 추가
- 각 사이드바 메뉴 클릭시 해당하는 route로 이동하도록 구현
- 사이드바를 추가해야 할 페이지를 선별하면 좋을 것 같습니다.
=> [Feat] 사이드바 공용 컴포넌트 구현

frontend/src/components/common/Sidebar.tsx, frontend/src/hooks/useTheme.ts, frontend/src/index.css, frontend/tailwind.config.js
> [!NOTE]
> 작성자: 서정우
> 작성 날짜: 2024.11.19
> 다크모드 구현, 사이드바에 다크모드를 토글하는 버튼을 추가했습니다. 
> 사이드바 헤더를 리뷰 받은 대로 수정 했습니다
- 다크모드 구현
- 다크모드 커스텀 훅
```ts
const useTheme = () => {
const [theme, setTheme] = useState<Theme>(
(localStorage.getItem("theme") as Theme) || "light"
);
useEffect(() => {
if (theme === "dark") {
document.documentElement.classList.add("dark");
} else {
document.documentElement.classList.remove("dark");
}
localStorage.setItem("theme", theme);
}, [theme]);
const toggleTheme = () => {
if (theme === "light") {
localStorage.setItem("theme", "dark");
setTheme("dark");
} else {
localStorage.setItem("theme", "light");
setTheme("light");
}
};
return { theme, toggleTheme };
};
```
사이드 바 우측 하단에 배치
- 다른 페이지들도 점진적으로 다크모드를 지원할 예정
=> [Feat] 다크모드 커스텀 훅 구현 및 다크모드 토글 버튼 추가

frontend/src/components/common/Toast.tsx, frontend/src/components/common/ToastProvider.tsx, frontend/src/hooks/useToast.ts, frontend/src/stores/useToastStore.ts, pnpm-lock.yaml
> [!NOTE]
> 토스트메시지를 리팩토링했습니다. 원래 고유아이디 문제를 해결하려고 했는데 하는 겸사겸사 토스트 스택 순서 방향도 변경했습니다. 
- 토스트 메시지 개선
- <ToastProvider/> 에서 렌더링하는 순서를 반대로 변경해서 자연스러운 애니메이션 유도
- 고유 ID에 랜덤한 값을 더하는 방식으로 중복확률 줄이기
- 현재는 생성된 시간을 ID로 사용하고 있다.
- 생성된 시간이 같다면? 실제로 소켓 이벤트 같은 경우 동시에 여러번 발생될 확률이 있고 실제 테스트 중에서도 여러 토스트 메시지가 동시에 발생한 적이 있었다.
- 그럴 때 5초 뒤 삭제되지 않고 남아있는 문제가 발생했었다. (같은 ID 토스트가 2개라면 1개만 사라지고 1개는 남는다)
- id + random 수 (0~200) 으로 하기로 결정
- 완전 고유한 아이디를 생성하기 위해 uuid 같은 라이브러리를 쓸 수도 있지만 라이브러리를 굳이 쓰고 싶지 않았다.
기존에는 새로 생긴 토스트 메시지를 아래에 추가하는 방식이었다.
아래에 추가하는 방식을 사용하니 문제점은 가장 위에 있는 토스트메시지가 먼저 사라지는 점이었다. 위 메시지가 사라지면 아래 메시지가 올라오는데, 이 부분이 뭔가 부자연스럽게 느껴졌다.
```tsx
// ToastProvider에서 반대로 렌더링해줄 수도 있지만 그 경우 reverse 하는 코스트가 든다.
// 새로운 토스트를 맨 앞에 추가해주는 방식으로 변경했다.
createToast: (toast: Toast) =>
set((state) => ({ toasts: [toast, ...state.toasts] …
```
=> [Refactor] Toast 메시지 리팩토링

frontend/package.json, frontend/src/components/common/SearchBar.tsx, frontend/src/components/common/Select.tsx, frontend/src/components/common/Sidebar.tsx, frontend/src/components/questions/QuestionsPreviewCard.tsx, frontend/src/components/sessions/SessionCard.tsx, frontend/src/main.tsx, frontend/src/pages/ErrorPage.tsx, frontend/src/pages/LoginPage.tsx, frontend/src/pages/QuestionListPage.tsx, frontend/src/pages/SessionListPage.tsx, frontend/tailwind.config.js
> [!NOTE]
> - 작성자: 이승윤
> - 작성 날짜: 2024.11.20
- tanstack query 설치
- 페이지 별 디자인 일부 통일
- 시간이 없어서 일부분만 수정했습니다.
- 생각보다 제가 UI를 신경 많이 못 썼는데 마음에 걸려서 조금 수정했습니다.
- 피그마 쓸 때는 몰랐는데 `폰트`가 많이 크다는 느낌을 받아서 줄였습니다. 줄여도 큰 편이긴 합니다. 😅
- 질문지 리스트 검색 바가 지나치게 길다는 느낌을 받았는데 어떤가요? 고민되네요.
- 해당 부분 UI도 고민을 좀 해봐야할 거 같습니다.
- 현재 제 화면이 커서 그렇긴한데, `노트북 사용자나 아이패드 사용자를 기준으로 width`를 정해두면 어떨까 싶습니다.
- 면접 스터디 특성상 여러 사람과 화면을 보고 소통하다보니 `모바일 사용자`를 고려하기보다(모바일에서 면접 연습을 한다는게 자신의 영상, 상대 영상, 질문까지 다 볼 수 있어야하는데 연습하기엔 무리가 아닌가 하는 생각이 듭니다. 무엇보다 실제 면접 연습을 하는 공간인데 실제 면접을 휴대폰으로 보는 사람은 거의 없지 않을까?하는 생각이 들었습니다.)는 태블릿 크기부터 고려하는게 좋을거 같다는 생각이 듭니다.
- 지금 스터디 세션 목록 페이지가 사이드바 제외하고 760px 정도 쯤 되는걸로 아는데 사이드바까지 하면 1000px이 넘습니다. 그럼 일반 노트북을 꽉채우게 될거 같은데, 이 정도로 너비를 정해두는거 어떨까요?
- 이런식으로 모니터 같은데서는 오른쪽 여백이 생기는거도 괜찮을거 같습니다. (사이드 바가 왼쪽에 위치하기 때문에 오른쪽 여백이 있는게 자연스러울거 같습니다.) …
=> [Design] 일부 페이지 디자인 통일 

.gitignore, docker-compose.yml
> - 작성자: 김찬우
> - 작성 날짜: 2024.11.21
- 없음 (편의성 기능)
- `docker-compose.yml` 추가
- 앞으로 `MySQL`, `Redis` 등 데브서버에 필요한 부가적인 서버들은 모두 `docker-compose.yml` 에서 실행가능
- `데브서버이므로 공개해도 된다고 판단했음`
```
version: '3'
services:
mysql:
image: mysql:latest
container_name: mysql
ports:
- '3306:3306'
environment:
MYSQL_ROOT_PASSWORD: dbcadmium
MYSQL_DATABASE: preview
TZ: Asia/Seoul
command:
- --character-set-server=utf8mb4
- --collation-server=utf8mb4_unicode_ci
volumes:
- ./mysql-data:/var/lib/mysql
redis:
image: redis:latest
container_name: redis
ports:
- '6379:6379'
command: redis-server --port 6379
volumes:
- ./redis-data:/data
```
그래서 이제 `.env` 만 공유하면 데브서버 환경 통일 가능합니다!
인텔리제이에서는 여기서 실행 가능
또는 도커 데스크탑에서 아래 명령어 실행
```bash
docker compose up -d
```
이후 도커 데스크탑에서 확인 가능
참 쉽죠???
- 배포 테스트 해야합니다!
- 태스크 마저 수행할게요. 질문지 핵심 기능 …
=> [Chore] docker compose 기능 추가

backend/src/room/room.repository.ts, backend/src/room/room.service.ts
> - 작성자: 김찬우
> - 작성 날짜: 2024.11.21
- `/api/rooms` 에서, 열려있는 세션이 없을 경우에 대한 예외처리
- 세션 리스트 API 데이터 수정
> 지금은 열려있는 세션이 없는 경우 즉, map 객체가 null 일 경우에 Object.entries(redisMap)에서 오류가 발생하고 있습니다. 간단하게 > redisMap ?? [] 혹은 ?? {} 혹은 ?? new Map()으로 처리하면 될 것 같습니다.
아래와 같이 수정했고, 비어있을 때 불러올때 에러가 없고, 빈 객체를 반환하도록 하였습니다.
```ts
async getPublicRoom() {
const rooms = await this.roomRepository.getAllRoom();
Object.keys(rooms ?? {}).forEach((roomId) => {
if (rooms[roomId].status === "PRIVATE") rooms[roomId] = undefined;
});
return rooms;
}
```
- 배열로 수정
- 필요한 데이터들을 반환하도록 수정
- 다만, 현재 당장 없는 기능은 모킹했음
- 예시 : category : "프론트엔드", nickname : "방장", participants: 1
```ts
async getPublicRoom() {
const rooms = await this.roomRepository.getAllRoom();
const roomList = [];
Object.entries(rooms).forEach(([roomId, roomData]) => {
if …
```
=> [Fix] 열려있는 세션이 없을 경우에 대한 예외처리, 세션 리스트 GET API 수정

backend/src/question-list/dto/create-question-list.dto.ts, backend/src/question-list/dto/question-list.dto.ts, backend/src/question-list/dto/question.dto.ts, backend/src/question-list/question-list.controller.ts, backend/src/question-list/question-list.module.ts, backend/src/question-list/question-list.repository.ts, backend/src/question-list/question-list.service.ts, backend/src/question-list/question.entity.ts, backend/src/room/dto/create-room.dto.ts, backend/src/room/room.gateway.ts, backend/src/room/room.model.ts, backend/src/room/room.module.ts, backend/src/room/room.repository.ts, backend/src/room/room.service.spec.ts, backend/src/room/room.service.ts
> - 작성자: 송수민
> - 작성 날짜: 2024.11.21
- 스터디룸 생성할 때 질문 내용 전달
- 질문지 기능 버그 fix
- 질문 내용의 길이를 20에서 200으로 늘리기
- 질문 리스트와 그 안의 질문을 생성하는 쿼리를 트랜잭션으로 묶기
- https://www.notion.so/API-5833448b99f940ef8a75ffaa3e15a4e7?pvs=4#ed5ec66a36c04536a146afdfde7e9aa2
- 기존에 질문 리스트가 생성된 후, 질문을 생성하는 쿼리를 구현했었는데, 질문을 생성하는 쿼리에서 문제가 발생하면 빈 질문 리스트가 생성되는 오류가 있었습니다.
- 이를 트랜잭션으로 묶어서 중간에 에러가 나면 아예 rollback 되도록 구현했습니다.
- 트랜잭션 사용을 위해 queryRunner라는 것을 사용했습니다.
```ts
// question-list.service.ts
async createQuestionList(createQuestionListDto: CreateQuestionListDto) {
const { title, contents, categoryNames, isPublic, userId } =
createQuestionListDto;
const categories = await this.findCategoriesByNames(categoryNames);
const queryRunner = this.dataSource.createQueryRunner();
await queryRunner.startTransaction();
try {
const …
```
=> [Feat] 스터디룸 생성에 질문 내용 전달, 질문지 기능 버그 fix

backend/src/room/room.gateway.ts, backend/src/signaling-server/sig-server.gateway.ts, backend/src/websocket/websocket.config.ts, backend/src/websocket/websocket.gateway.ts
> - 작성자: 김찬우
> - 작성 날짜: 2024.11.26
- 세션 리워크 중 누락된 CORS 설정을 허용하였습니다.
- `config` 파일을 분리하여서 설정 값을 저장합니다!
- 갑자기 든 생각인데 `CORS`를 진짜 모두 허용해도 될지 의문이었습니다.
- 그래서 새롭게 프로덕션 환경에서는 저희 도메인만 허용할 수 있도록 이렇게 설정하였습니다.
- 프로덕션 환경에서는 특정 도메인만 허용하도록 조절할 수 있게 했습니다.
- `dev-be` 에 업로드 되어있으니 프론트엔드분들은 참고하셔서 가져오시길 바랍니다!
```ts
// websocket.config.ts
export const websocketConfig = {
cors: {
origin: process.env.DOMAIN || "*",
},
};
```
=> [Fix] websocket gateway CORS 허용

backend/src/question-list/question-list.controller.ts, backend/src/question-list/question-list.entity.ts, backend/src/question-list/question-list.module.ts, backend/src/question-list/question-list.repository.ts, backend/src/question-list/question-list.service.ts, backend/src/question-list/question.entity.ts, backend/src/user/dto/user.dto.ts, backend/src/user/user.entity.ts
> - 작성자: 송수민
> - 작성 날짜: 2024.11.26
- #133 
- #134 
- #218 
- #219 
- #232 
- #233 
- 스크랩 기능을 위한 user_question_list 엔티티 구현
- 질문지 스크랩 기능 구현
- 스크랩한 질문지 조회 기능
- 질문지 스크랩 기능
- 스크랩한 질문지 스크랩 취소(unscrap) 기능
- 스크랩 기능을 위해 user와 question_list 테이블을 다대다 관계로 연결해줘야 했습니다.
- typeorm의 ManyToMany로 User entity 파일에 다대다 관계를 설정해줬습니다.
- 둘 중 user에 관계를 정의한 이유는`다대다 관계일 경우 관계의 주체가 되는 테이블에 ManyToMany 정의를 하는 것이 일반적이다.`라고 배웠기 때문입니다. 
```ts
// user.entity.ts
import { Entity, PrimaryGeneratedColumn, Column, OneToMany, ManyToMany, JoinTable } from "typeorm";
import { QuestionList } from "@/question-list/question-list.entity";
@Entity()
export class User {
private static LOGIN_ID_MAX_LEN = 20;
private static PASSWORD_HASH_MAX_LEN = 256;
private static USERNAME_MAX_LEN = 20;
private static REFRESH_TOKEN_MAX_LEN = 200; …
```
=> [Feat] 질문지 스크랩 기능(조회, 스크랩, 스크랩 취소) 구현

backend/package.json, backend/src/app.module.ts, backend/src/main.ts, backend/src/room/room.entity.ts, backend/src/room/room.module.ts, backend/src/room/room.repository.ts, backend/src/websocket/websocket.entity.ts, backend/src/websocket/websocket.module.ts, backend/src/websocket/websocket.repository.ts, pnpm-lock.yaml
> - 작성자: 김찬우
> - 작성 날짜: 2024.11.27
- `nestjs-redis-om` 모듈을 수정해서 오류를 해결했습니다.
저 패키지 출시했어요. 축하해주세요.
[들어가보기](https://www.npmjs.com/package/@moozeh/nestjs-redis-om)
`MIT` 라이선스에 따라 원저자 출처를 해서 출시를 했습니다.
아래 `nestjs-redis-om` 코드를 수정할 필요가 있었습니다.
```ts
const schema = new Schema(
entityMetadata.schemaName,
entityMetadata.fields,
entityMetadata.schemaOptions,
);
const repository = new Repository(schema, dataSource);
await repository.createIndex();
return repository;
```
이부분에서 인덱스 생성 시, 이미 존재하거나 상태가 동일하지 않을 경우 에러처리를 하지 않던 것이 문제였습니다.
실제로 `nestjs` 를 위한 `redis-om` 래퍼가 없었고, 다른 사람들도 불편함을 느꼈을 것으로 판단했습니다.
그래서 이왕 하는 김에 실제로 배포까지 진행했습니다. 추후에 `Schema` 기능 중에 `TTL` 설정하는 것까지 지원해볼 생각입니다.
- 스터디 기능을 위한 웹소켓 핸들러를 만들 생각입니다.
- 저 패키지 출시했어요 축하해줘요 🐥🐥
=> [Fix] index already exists 문제 해결 (패키지 출시함)

backend/src/room/dto/move-index.dto.ts, backend/src/room/dto/room-id.dto.ts, backend/src/room/dto/room.dto.ts, backend/src/room/room.entity.ts, backend/src/room/room.events.ts, backend/src/room/room.gateway.ts, backend/src/room/room.repository.ts, backend/src/room/services/room-create.service.ts, backend/src/room/services/room-join.service.ts, backend/src/room/services/room.service.ts
> - 작성자: 김찬우
> - 작성 날짜: 2024.11.27
- 작업한 주요 기능 및 수정 사항
- 하루 동안 진행된 핵심적인 변경사항 간단 정리
- 스터디 룸에 현재 질문지 위치 상태를 추가 해야했고, 그리고 추가적으로 최대 질문지 인덱스도 추가했습니다.
- 스토리지 자체에 질문지를 받고 있지 않기 때문에 질문지 개수만 추가했습니다!
```ts
import { Entity, Field, Schema } from "nestjs-redis-om";
export interface Connection {
socketId: string;
nickname: string;
createAt: number;
}
export enum RoomStatus {
PUBLIC = "PUBLIC",
PRIVATE = "PRIVATE",
}
@Schema("room", {})
export class RoomEntity extends Entity {
@Field({ type: "string", indexed: true })
id: string;
@Field({ type: "string" })
title: string;
@Field({ type: "string[]" })
category: string[];
@Field({ type: "boolean" })
inProgress: boolean;
@Field({ type: "number" })
currentIndex: number;
@Field({ type: "string" })
status: RoomStatus;
@Field({ type: "number" }) …
```
=> [Feat] 스터디 기능을 위한 웹소켓 API 추가

backend/src/user/dto/update-user.dto.ts, backend/src/user/dto/user.dto.ts, backend/src/user/user.controller.ts, backend/src/user/user.entity.ts, backend/src/user/user.repository.ts, backend/src/user/user.service.ts
> - 작성자: 김찬우
> - 작성 날짜: 2024.11.28
- (이슈 번호 작성) # (작성예정)
- 유저 수정 / 조회를 위한 DTO 추가
- 유저 아바타등록을 위한 엔티티에 아바타필드 추가 
- 유저 관련 비즈니스 로직 추가
- 유저 레포지토리 기능 추가
- 핸들러를 위한 DTO를 추가했습니다.
- 유저 엔티티에 아바타 필드를 추가했습니다.
- 비밀번호 변경
- 유저 메타 데이터 업데이트 기능
- 로컬로 로그인할 수 있도록 하는 회원가입 기능
- 아이디로 엔티티 검색 가능한 기능을 추가했습니다!
- 추후 인덱싱해야하는데, 그냥 같은 PK로 둘지도 고민입니다.
- POSTMAN으로 실행하였습니다.
- 수정, 인증, 조회 모두 가능합니다!
- 이 PR 다음 본 PR을 확인해주세요.
- 수민님 : 유저 엔티티 수정이 올바른지, 바뀐건 없는지 확인만 해주세요!
- 승윤님 : 원하는 명세대로 나왔는지, 더 원하시는 건 없는지 알려주세요!
=> #260-1 [Feat] 유저 메타데이터 관련 API 추가

backend/src/auth/auth.controller.ts, backend/src/auth/github/github.strategy.ts, backend/src/auth/jwt/jwt.decorator.ts, backend/src/auth/jwt/jwt.service.ts, backend/src/auth/jwt/strategy/refresh-token.strategy.ts, backend/src/user/dto/update-user.dto.ts, backend/src/user/dto/user.dto.ts, backend/src/user/user.controller.ts, backend/src/user/user.entity.ts, backend/src/user/user.repository.ts, backend/src/user/user.service.ts, backend/src/utils/time.ts
> [!note]
>
> 한꺼번에 많은 PR을 올리지 않도록 분리하였습니다.
> #260
> 을 먼저 확인해주세요. 이 PR과 연관되어있어서 이 PR 이 머지되면 저곳도 머지 됩니다.
- 시간 정보 수정
- JWT 토큰 만료 기간 버그 수정
- 전략 패턴 수정
지금 보여주는 코드는 이전 코드 입니다!
- 1초는 1000 밀리 세컨드 ..
```ts
// utils/time.ts
export const SEC = 1; // ?????? 
export const MIN = 60 * SEC;
export const HOUR = 60 * MIN;
export const DAY = 24 * HOUR;
```
- JWT 토큰 설정 시, 설정 시간이 잘못되어있었습니다.
- 만료 기간을 설정해야하는데, 만료 시간으로 설정하였습니다.
- 그렇게돼서 무려 만료시간이 1년 뒤.. 로 설정되는 버그가 있었고, 해결했습니다.
```ts
// jwt.service.ts
public async createAccessToken(user: User): Promise<IJwtToken> {
const accessToken = this.parent.sign(
{
userId: user.id,
username: user.username,
},
{
secret: process.env.JWT_ACCESS_TOKEN_SECRET_KEY,
expiresIn: process.env.JWT_ACCESS_TOKEN_EXPIRATION_TIME,
}
);
return {
token: accessToken,
expireTime: Date.now() + …
```
=> #260-2 [Fix] 시간 정보 수정, JWT 토큰 만료 기간 버그 수정, 전략 패턴 수정 (#260 확인)

backend/src/auth/auth.controller.ts, backend/src/auth/auth.module.ts, backend/src/auth/auth.service.ts, backend/src/auth/dto/login.dto.ts, backend/src/auth/github/github.strategy.ts, backend/src/auth/jwt/jwt.decorator.ts, backend/src/auth/jwt/jwt.service.ts, backend/src/auth/jwt/strategy/refresh-token.strategy.ts, backend/src/auth/local/local.strategy.ts, backend/src/config/cookie.config.ts, backend/src/user/dto/create-user.dto.ts, backend/src/user/dto/update-user.dto.ts, backend/src/user/dto/user.dto.ts, backend/src/user/user.controller.ts, backend/src/user/user.entity.ts, backend/src/user/user.module.ts, backend/src/user/user.repository.ts, backend/src/user/user.service.ts, backend/src/utils/time.ts
> [!note]
>
> 한꺼번에 많은 PR을 올리지 않도록 분리하였습니다. (제가 코드를 빨리치다보니 이걸 좀 분리하고싶은데 고민이네요.)
> #260 
> #261
> 을 먼저 확인해주세요. 이 PR과 연관되어있어서 이 PR 이 머지되면 저곳도 머지 됩니다.
> - 작성자: 김찬우
> - 작성 날짜: 2024.11.28
- #13 
- #12 
- 로그인 회원가입 기능을 위한 DTO 추가 
- 로그인 기능을 위한 passport 전략 추가
- 쿠키 설정 시 secure 값을 production 일때만 되도록 허용
- 회원가입을 위한 DTO 추가
- 로그인을 위한 DTO 추가
- DTO가 좀 여러개 변경사항을 확인해보셔야할 거에요.
- `저한테 말 거시면 상세히 알려드리겠습니다.`
- 실제 인증은 `auth` 에서 합니다.
- 유저는 유저 정보 자체를 다루는데 집중하고, 해야할 것 같았습니다.
- 패스워드 해시 생성도 인증쪽에서 다루도록 바꾸었습니다.
```ts
import { Strategy } from "passport-local";
import { PassportStrategy } from "@nestjs/passport";
import { Injectable, UnauthorizedException } from "@nestjs/common";
import { JwtService } from "@/auth/jwt/jwt.service";
import { AuthService } from "@/auth/auth.service";
@Injectable()
export class LocalStrategy …
```
=> #260-3 [Feat] 로그인 / 회원가입 기능 구현

backend/src/question-list/question-list.service.ts
> [!Note]
> 리뷰 해주시면 제가 merge 하겠습니다!
> - 작성자: 송수민
> - 작성 날짜: 2024.11.28
- 질문 삭제 서비스 로직에 transactional() 추가
- 특정 질문이 하나 삭제되면 남은 질문들의 순서도 업데이트 해줘야합니다.
- 현재 질문 삭제 로직에서는 질문이 하나 삭제되면 그 다음 질문들의 index를 하나씩 줄여주고 있습니다.
- 수정이 필요한 질문 갯수만큼 디비에 여러번 접근하고 있어서 transaction으로 묶어줘야했으나, 잊어버렸습니다...
- 그래서 아래와 같이 제일 위에 추가해주었습니다.
```ts
@Transactional()
async deleteQuestion(deleteQuestionDto: DeleteQuestionDto) {
const { id, questionListId, userId } = deleteQuestionDto;
const question = await this.questionListRepository.getQuestionById(id);
if (!question) throw new Error("Question not found.");
const user = await this.userRepository.getUserByUserId(userId);
if (!user) throw new Error("User not found.");
const questionList = await this.questionListRepository.getQuestionListById(questionListId);
if (!questionList) …
```
=> [Fix] 질문 삭제 로직에 transactional() 추가

frontend/src/components/questions/detail/QuestionList.tsx/index.tsx, frontend/src/components/questions/detail/QuestionTitle.tsx/index.tsx, frontend/src/components/session/Sidebar/SessionSidebar.tsx, frontend/src/hooks/__test__/useSession.test.ts, frontend/src/pages/QuestionDetailPage.tsx
> - 작성자: 이승윤
> - 작성 날짜: 2024.11.28
- 리액트 쿼리 훅에서 반환하지 않는 값 제거
- 로직 바뀐 테스트 코드 주석 처리
- 이전 모달 로직 사용되는 곳 수정
=> [Fix] 프론트엔드 빌드 오류 수정

frontend/src/components/mypage/CategoryTab/index.tsx, frontend/src/components/mypage/QuestionList/index.tsx, frontend/src/hooks/session/useSession.ts, frontend/src/hooks/session/useStudy.ts, frontend/src/pages/MyPage/view/Profile.tsx, frontend/src/pages/MyPage/view/ProfileEditModal.tsx, frontend/src/pages/MyPage/view/QuestionSection.tsx
=> [Fix] 빌드 에러 수정

backend/src/user/user.repository.ts, backend/src/user/user.service.ts
- 닉네임 생성 시 에러코드 400 번 출력되도록 수정
- 유저의 잘못된 요청이므로 Bad request가 적절하다고 판단
- 유저 생성 시 에러코드 출력되도록 수정
- 유저의 잘못된 요청이므로 Bad request가 적절하다고 판단했습니다.
- 이제 드뮴님을 한분 밖에 생성하지 못합니다.(?)
- 열심히 리팩토링 중입니다.
- `DDD` 쪽을 참고해서 도메인 쪽에서도 스스로 간단한 동작을 수행할 수 있게 책임분리 중입니다.
- 인프라쪽도 관심 분리중입니다~ 웹소켓인데 redis client 쪽도 담당하고 있더라고요.
- 레포지토리도 DB 접근만 책임지도록 관심분리중입니다!
- 서비스도 그냥 통합중입니다. 멘토님 피드백 이후, 코드 수보다 책임이 중요하다고 판단했기 때문입니다.
- `혹시 모르니,, if 문 맞는지만 확인해주세요!`
=> [Fix] 중복 닉네임 요청 시 400번 반환되도록 수정

backend/src/app.module.ts, backend/src/question-list/dto/question-list.dto.ts, backend/src/question-list/question-list.service.ts, backend/src/question-list/repository/category.repository.ts, backend/src/question-list/repository/question-list.repository.ts, backend/src/question-list/repository/question.respository.ts, backend/src/question/question.module.ts, backend/src/room/services/room-create.service.ts
> [!Note]
> - 작성자: 송수민
> - 작성 날짜: 2024.12.03
- 기존 repository가 base repository를 상속 받도록 리팩토링
- 트랜잭션 범위 최소화
- 기존 코드에서는 base repository를 상속받지 않고 직접 dataSource로 쿼리 빌더를 생성했었습니다.
```ts
// question-list.repository.ts
export class QuestionListRepository {
constructor(private dataSource: DataSource) {}
save(questionList: QuestionList) {
this.dataSource.getRepository(QuestionList).save(questionList); // 이렇게 save 함수를 직접 구현해줘야 했었음.
}
}
```
- 이 방식의 문제점은 base repository가 제공해주는 기본 메서드(save, find 등)을 서비스 계층에서 바로 사용하지 못하고, repository 계층에 새로 구현을 해줘야한다는 점이었습니다. 
- 이는 굳이 구현할 필요 없는 간단한 로직들을 모두 repository 계층에 구현하고 관리해줘야한다는 문제점이 있었고, 이를 해결하기 위해 base repository를 상속받도록 개선했습니다.
```ts
// question-list.repository.ts
export class QuestionListRepository extends Repository<QuestionList> {
constructor(private dataSource: …
```
=> [Refactor] base Repository 상속 & 트랜잭션 범위 최소화

backend/src/auth/auth.controller.ts, backend/src/auth/jwt/jwt.service.ts, backend/src/auth/jwt/strategy/refresh-token.strategy.ts, frontend/src/api/config/axios.ts, frontend/src/api/user/auth.ts, frontend/src/components/questions/create/QuestionInputSection/QuestionInput.tsx, frontend/src/pages/Login/AuthCallbackPage.tsx, frontend/src/pages/Login/hooks/useValidate.ts, frontend/src/pages/Login/view/OAuthContainer.tsx, frontend/src/pages/MyPage/MyPage.tsx, frontend/src/pages/QuestionListPage/view/Tabs.tsx, frontend/src/routes.tsx
- axios 인스턴스를 사용하는 요청에 대한 응답으로 401에러가 발생할 경우에 대한 처리를 일관적으로 하기 위해 인터셉터 도입
- 리프레시 토큰으로 재발급 시도하고 성공하면 요청 재시도
- 실패할 경우에는 세션 만료 alert 출력 후 로그인하도록 
- 원래 10자였는데 5자로 줄였습니다. 테스트하면서 10자 좀 불편했어서 바꿨는데 10자보다 적은 질문도 있고해서 괜찮은 것 같습니다.
=> [Feat] 401에러에 대한 처리 axios 인터셉터 사용, 최소 질문 길이 5자로 수정

backend/src/room/dto/all-room.dto.ts, backend/src/room/room.controller.ts, backend/src/room/services/room.service.ts
> [!note]
> - 작성자: 김찬우
> - 작성 날짜: 2024.12.03
- `GET /api/rooms` 요청에 대해 필터링 추가 옵션 제공
- `queryParam` 으로 `inProgress` 에 `true` 혹은 `false` 등으로 추가 필터링 가능
- 명세서도 수정해두었습니다.
- `/api/rooms?inProgress=true` 이렇게 쓰면 됩니다.
- Postman 으로 테스트 후 잘 작동!
=> [Feat] `GET /api/rooms` 요청에 대해 필터링 추가 옵션 제공

backend/src/question-list/dto/get-all-question-list.dto.ts, backend/src/question-list/dto/question-list-contents.dto.ts, backend/src/question-list/question-list.controller.ts, backend/src/question-list/question-list.service.ts, backend/src/question-list/repository/question-list.repository.ts
> [!Note]
> - 작성자: 송수민
> - 작성 날짜: 2024.12.04
- 모든 API 응답에 적절한 상태 코드 반환
- 로그인이 필요한 API에 401 상태 코드 반환
- internal server error의 경우 500 상태 코드 반환
- 로그인 유무에 따라 적절한 응답 반환 
- `isScrap`: boolean
- 전체 질문지 조회
- 카테고리별 질문지 조회
- 질문지 상세 페이지 
- `scrapCount`: boolean
- 질문지 상세 페이지
- 로그인하지 않은 유저는 모두 `false` 반환
- 질문지 작성자 관련 에러 fix
- 기존에는 응답의 성공 유무와 관계없이 200이나 201 상태 코드를 반환했었습니다.
- 상태 코드를 정확하게 반환해달라는 정우님의 요청으로 모든 API 요청이 적절한 상태 코드를 반환할 수 있도록 수정했습니다.
```ts
@Get("my")
@UseGuards(AuthGuard("jwt"))
@UsePipes(new ValidationPipe({ transform: true }))
async getMyQuestionLists(
@Res() res,
@Query() query: PaginateQueryDto,
@JwtPayload() token: IJwtPayload
) {
try {
const userId = token ? token.userId : null;
if (!userId)
return res.status(HttpStatus.UNAUTHORIZED).json({ // 401 반환
success: false,
message: "Login …
```
=> [Refactor] 로그인 유무에 따른 에러 처리와 응답 반환

frontend/vite.config.ts
빌드에러 수정, vendor 파일로 리액트 라이브러리 별도의 청크 파일 분리
라이브러리용 빌드 라이브러리 분리 설정을 써서 배포가 안됐던 것 같습니다. vendor 파일로 분리해서 더 최적화하고 오류도 수정했습니다.
=> [Fix] 빌드에러 수정, vendor 파일로 리액트 라이브러리 별도의 청크 파일 분리

frontend/src/components/session/MediaPreviewModal.tsx, frontend/src/pages/SessionPage/hooks/useBlockNavigate.ts, frontend/src/pages/SessionPage/hooks/useMediaDevices.ts, frontend/src/pages/SessionPage/hooks/usePeerConnection.ts, frontend/src/pages/SessionPage/hooks/useSession.ts
- 비디오 끄고 참가하면 사람들 비디오가 안보이던 문제를 해결했습니다.
- 이거 문제도 좀 문서화해야겠네요
=> [Fix] 비디오 끄고 참가시 안보이던 문제 해결

frontend/src/api/question-list/getQuestionContent.ts, frontend/src/components/sessions/create/SessionForm/CategorySection.tsx, frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/QuestionItem.tsx, frontend/src/components/sessions/create/SessionForm/ListSelectModal/QuestionList/index.tsx, frontend/src/components/sessions/create/SessionForm/ListSelectModal/index.tsx, frontend/src/components/sessions/create/SessionForm/TitleSection.tsx, frontend/src/constants/CategoryData.ts, frontend/src/pages/CreateSessionPage/CreateSessionPage.tsx, frontend/src/pages/CreateSessionPage/stores/useSessionFormStore.ts, frontend/src/pages/CreateSessionPage/view/SessionForm.tsx
> [!NOTE]
> 세션 생성 페이지에서 내가 만든, 내가 스크랩한 질문지를 선택할 수 있게 구현했습니다. 몇몇 UX측면 리팩토링 진행했습니다.
- 세션 생성시 내가 만든 질문지, 스크랩한 질문지 조회 기능 구현
- 모달 내 조회에 페이지네이션 도입
- 기존: 체크 박스를 클릭해야만 선택, 변경: 질문지 아이템 자체를 클릭해도 선택되도록 수정
- 질문지 아이템 선택하면 자동으로 열리도록 수정
- 몇몇 코드 중복제거
- 세션 이름이 5글자가 되면 빨간글씨는 없어지지만 세션 생성이 되지 않던 문제 해결
- 질문지 선택 모달에서 질문지가 없을 경우 NotFound 컴포넌트를 렌더링
지금 보니 버튼이 없어도 될 것 같기도..
- 리액트 쿼리 부분
=> [Refactor] 세션 생성시 질문지 선택하는 부분에서 내가 만든, 스크랩한 질문지 조회 가능하도록 구현 및 리팩토링
